Valeris: CodeGuesser Class Reference
CodeGuesser Class Reference
Public Member Functions
CodeGuesser ()
void start ()
bool addGuess ()
void printGuesses ()
void printWords ()
Static Private Member Functions
static int generateRandomIndex (size_t size)
Private Attributes
std::vector< std::string > words
std::vector< std::string > guesses
int index
Detailed Description
CodeGuesser game
Definition at line 138 of file minigames.cpp.
Constructor & Destructor Documentation
CodeGuesser()
CodeGuesser::CodeGuesser () inline
Definition at line 159 of file minigames.cpp.
        : words(split(getFileContent("../reasources/cg_words.txt"), '\n')),
          index(generateRandomIndex(words.size())) {}
Member Function Documentation
addGuess()
bool CodeGuesser::addGuess () inline
Definition at line 191 of file minigames.cpp.
    {
        // Yellow, Green, Reset
        std::string colorCodes[] = {"\033[43m", "\033[42m", "\033[0m"};
        std::string guess, coloredGuess;
        std::cin >> guess;
        bool correct = true;
        for (int i = 0; i < 5; i++)
        {
            if (words.at(index).at(i) == guess.at(i))
            {
                coloredGuess.append(colorCodes[1] + guess.substr(i, 1) + colorCodes[2] + " ");
                continue;
            }
            else
            {
                correct = false;
            }
            bool contains = false;
            for (int j = 0; j < 5; j++)
            {
                if (words.at(index).at(j) == guess.at(i))
                {
                    contains = true;
                    break;
                }
            }
            if (contains)
            {
                coloredGuess.append(colorCodes[0] + guess.substr(i, 1) + colorCodes[2] + " ");
            }
            else
            {
                coloredGuess.append(guess.substr(i, 1) + " ");
            }
        }
        guesses.push_back(coloredGuess);
        return correct;
    }
References guesses, index, and words.
Referenced by start().
generateRandomIndex()
static int CodeGuesser::generateRandomIndex (size_t size) inline static private
Definition at line 146 of file minigames.cpp.
    {
        if (size == 0)
        {
            throw std::invalid_argument("Size of words vector must be greater than 0");
        }
        std::random_device rd;                            // Seed
        std::mt19937 gen(rd());                           // Mersenne Twister engine
        std::uniform_int_distribution<> dis(0, size - 1); // Distribution range
        return dis(gen);
    };
printGuesses()
void CodeGuesser::printGuesses () inline
Definition at line 233 of file minigames.cpp.
    {
        for (const auto &guess : guesses)
        {
            std::cout << guess << "\n";
        }
        std::cout << +"\npasscode: ";
    }
References guesses.
Referenced by start().
printWords()
void CodeGuesser::printWords () inline
Definition at line 242 of file minigames.cpp.
    {
        for (int i = 0; i < words.size(); i++)
        {
            std::cout << words.at(i) + "\n";
        }
    }
References words.
start()
void CodeGuesser::start () inline
Definition at line 163 of file minigames.cpp.
    {
        bool success = false;
        int count = 0;
        while (count < 5)
        {
            std::cout << "Please enter the five lettered passcode: " + std::to_string(5 - count) + " guesses remaining\n\n";
            printGuesses();
            if (addGuess())
            {
                success = true;
                break;
            }
            clear(4 + count);
            count++;
        }
        if (success)
        {
            std::cout << "Passcode Accepted!";
        }
        else
        {
            std::cout << "Too many failed attempts! Please restart";
        }
    }
References addGuess(), clear(), and printGuesses().
Referenced by main().
Field Documentation
guesses
std::vector<std::string> CodeGuesser::guesses private
Definition at line 143 of file minigames.cpp.
Referenced by addGuess(), and printGuesses().
index
int CodeGuesser::index private
Definition at line 144 of file minigames.cpp.
Referenced by addGuess().
words
std::vector<std::string> CodeGuesser::words private
Definition at line 142 of file minigames.cpp.
Referenced by addGuess(), and printWords().
The documentation for this class was generated from the following file:
helper/minigames.cpp