Valeris: Dungeon Class Reference
Dungeon Class Reference
Public Member Functions
Dungeon ()
~Dungeon ()
Room * generateFloor (int numRooms)
void traverseAndPrint (Room *startRoom)
Private Member Functions
Room * generateRoom ()
void linkRooms (Room *room1, Room *room2, int direction)
Private Attributes
std::vector< Room * > rooms
std::mt19937 rng
Detailed Description
Definition at line 22 of file dungeon.cpp.
Constructor & Destructor Documentation
Dungeon()
Dungeon::Dungeon () inline
Definition at line 59 of file dungeon.cpp.
: rng(std::time(0)) {}
~Dungeon()
Dungeon::~Dungeon () inline
Definition at line 61 of file dungeon.cpp.
    { // Deconstructor
        for (Room *room : rooms)
        {
            delete room;
        }
    }
References rooms.
Member Function Documentation
generateFloor()
Room * Dungeon::generateFloor (int numRooms) inline
Definition at line 69 of file dungeon.cpp.
    {
        if (numRooms <= 0)
        {
            return nullptr;
        }
        Room *startRoom = generateRoom();
        for (int i = 1; i < numRooms; ++i)
        {
            Room *existingRoom;
            int direction;
            do
            {
                existingRoom = rooms[std::uniform_int_distribution<>(0, rooms.size() - 1)(rng)];
                direction = std::uniform_int_distribution<>(0, 3)(rng);
            } while (
                (direction == 0 && existingRoom->north != nullptr) ||
                (direction == 1 && existingRoom->south != nullptr) ||
                (direction == 2 && existingRoom->west != nullptr) ||
                (direction == 3 && existingRoom->east != nullptr)); // Making sure it is not overwriting
            Room *newRoom = generateRoom();
            linkRooms(existingRoom, newRoom, direction); // linking rooms
        }
        return rooms[std::uniform_int_distribution<>(0, rooms.size() - 1)(rng)];
    }
References Room::east, generateRoom(), linkRooms(), Room::north, rng, rooms, Room::south, and Room::west.
Referenced by main().
generateRoom()
Room * Dungeon::generateRoom () inline private
Definition at line 28 of file dungeon.cpp.
    {
        Room *newRoom = new Room();
        rooms.push_back(newRoom);
        return newRoom;
    }
References rooms.
Referenced by generateFloor().
linkRooms()
void Dungeon::linkRooms (Room * room1, Room * room2, int direction) inline private
Definition at line 35 of file dungeon.cpp.
    {
        switch (direction)
        {
        case 0: // North
            room1->north = room2;
            room2->south = room1;
            break;
        case 1: // South
            room1->south = room2;
            room2->north = room1;
            break;
        case 2: // West
            room1->west = room2;
            room2->east = room1;
            break;
        case 3: // East
            room1->east = room2;
            room2->west = room1;
            break;
        }
    }
References Room::east, Room::north, Room::south, and Room::west.
Referenced by generateFloor().
traverseAndPrint()
void Dungeon::traverseAndPrint (Room * startRoom) inline
Definition at line 99 of file dungeon.cpp.
    { // Traverse the floor (used for testing or can create floor maps)
        if (startRoom == nullptr)
            return;
        std::queue<std::pair<Room *, std::pair<int, int>>> q;
        std::map<std::pair<int, int>, Room *> visited;
        q.push({startRoom, {0, 0}});
        visited[{0, 0}] = startRoom;
        while (!q.empty()){
            auto [currentRoom, coords] = q.front();
            q.pop();
            int x = coords.first;
            int y = coords.second;
            std::cout << "Room at (" << x << ", " << y << "): " << currentRoom->content << std::endl;
            if (currentRoom->north && visited.find({x, y + 1}) == visited.end())
            {
                q.push({currentRoom->north, {x, y + 1}});
                visited[{x, y + 1}] = currentRoom->north;
            }
            if (currentRoom->south && visited.find({x, y - 1}) == visited.end())
            {
                q.push({currentRoom->south, {x, y - 1}});
                visited[{x, y - 1}] = currentRoom->south;
            }
            if (currentRoom->east && visited.find({x + 1, y}) == visited.end())
            {
                q.push({currentRoom->east, {x + 1, y}});
                visited[{x + 1, y}] = currentRoom->east;
            }
            if (currentRoom->west && visited.find({x - 1, y}) == visited.end())
            {
                q.push({currentRoom->west, {x - 1, y}});
                visited[{x - 1, y}] = currentRoom->west;
            }
        }
    }
References Room::content.
Referenced by main().
Field Documentation
rng
std::mt19937 Dungeon::rng private
Definition at line 26 of file dungeon.cpp.
Referenced by generateFloor().
rooms
std::vector<Room *> Dungeon::rooms private
Definition at line 25 of file dungeon.cpp.
Referenced by generateFloor(), generateRoom(), and ~Dungeon().
The documentation for this class was generated from the following file:
helper/dungeon.cpp