Valeris: TicTacToe Class Reference
TicTacToe Class Reference
Public Member Functions
void printBoard ()
void computerTurn ()
bool checkForWin ()
void startGame ()
Private Attributes
char squares [3][3]
Detailed Description
Definition at line 4 of file minigames.cpp.
Member Function Documentation
checkForWin()
bool TicTacToe::checkForWin () inline
Definition at line 43 of file minigames.cpp.
    {
        bool wasWin = false;
        // Horizontal Check
        for (int i = 0; i < 3; i++)
        {
            if (squares[i][0] == squares[i][1] && squares[i][0] == squares[i][2] && squares[i][0] != ' ')
            {
                wasWin = true;
            }
        }
        // Vertical check
        for (int i = 0; i < 3; i++)
        {
            if (squares[0][i] == squares[1][i] && squares[0][i] == squares[2][i] && squares[0][i] != ' ')
            {
                wasWin = true;
            }
        }
        // Diagonal Check
        if (squares[0][0] == squares[1][1] && squares[0][0] == squares[2][2] && squares[0][0] != ' ')
        {
            wasWin = true;
        }
        if (squares[0][2] == squares[1][1] && squares[0][2] == squares[2][0] && squares[0][2] != ' ')
        {
            wasWin = true;
        }
        return wasWin;
    }
References squares.
Referenced by startGame(), and testTicTacToeInitialization().
computerTurn()
void TicTacToe::computerTurn () inline
Definition at line 24 of file minigames.cpp.
    {
        std::srand(static_cast<unsigned int>(std::time(nullptr)));
        while (true)
        {
            int row = std::rand() % 3;
            int col = std::rand() % 3;
            if (squares[row][col] == ' ')
            {
                squares[row][col] = 'O';
                break;
            }
        }
        std::cout << "\n\n";
        clear(12);
        printBoard();
    }
References clear(), printBoard(), and squares.
Referenced by startGame().
printBoard()
void TicTacToe::printBoard () inline
Definition at line 12 of file minigames.cpp.
    {
        std::string arr[2] = {"\n   |   |   ", "\n___|___|___"};
        std::string top = std::string("\n ") + squares[0][0] + " | " + squares[0][1] + " | " + squares[0][2] + " ";
        std::string middle = std::string("\n ") + squares[1][0] + " | " + squares[1][1] + " | " + squares[1][2] + " ";
        std::string bottom = std::string("\n ") + squares[2][0] + " | " + squares[2][1] + " | " + squares[2][2] + " ";
        std::cout << arr[0] + top + arr[1] + arr[0] + middle + arr[1] + arr[0] + bottom + arr[0] << std::endl;
        std::cout.flush();
    }
References squares.
Referenced by computerTurn(), and startGame().
startGame()
void TicTacToe::startGame () inline
Definition at line 76 of file minigames.cpp.
    {
        printBoard();
        int row, col;
        int count = 0;
        while (true)
        {
            std::cout << "\nEnter your move (row and column separated by a space, e.g., '1 1'): ";
            std::cin >> row >> col;
            if (std::cin.fail() || row < 1 || row > 3 || col < 1 || col > 3)
            {
                std::cin.clear();            // clear the error flag on cin
                std::cin.ignore(1000, '\n'); // discard invalid input
                std::cout << "Invalid input. Please enter numbers between 1 and 3." << std::endl;
                continue;
            }
            if (squares[row - 1][col - 1] != ' ')
            {
                std::cout << "That square is already taken. Please choose another one." << std::endl;
                continue;
            }
            squares[row - 1][col - 1] = 'X';
            clear(12);
            printBoard();
            if (checkForWin())
            {
                std::cout << "You win!" << std::endl;
                break;
            }
            count++;
            if (count == 9)
            {
                std::cout << "Draw!" << std::endl;
                break;
            }
#ifdef _WIN32
            Sleep(1); // Sleep for 1 second
#else
            sleep(1);
#endif
            computerTurn();
            if (checkForWin())
            {
                std::cout << "You lose!" << std::endl;
                break;
            }
            count++;
            if (count == 9)
            {
                std::cout << "Draw!" << std::endl;
                break;
            }
        }
    }
References checkForWin(), clear(), computerTurn(), printBoard(), and squares.
Field Documentation
squares
char TicTacToe::squares[3][3] private
Initial value:
=
        {
            {' ', ' ', ' '}, {' ', ' ', ' '}, {' ', ' ', ' '}}
Definition at line 7 of file minigames.cpp.
Referenced by checkForWin(), computerTurn(), printBoard(), and startGame().
The documentation for this class was generated from the following file:
helper/minigames.cpp