Valeris: helper/toolkit.cpp File Reference
toolkit.cpp File Reference
#include "../lib/dependencies.h"
#include <sys/ioctl.h>
#include <unistd.h>
#include <termios.h>
Functions
void SetTerminalSize (int height, int width)
void delay (int milliseconds)
void disableInput ()
void enableInput ()
void typePrint (std::string content)
std::string getFileContent (std::string fileName)
std::vector< std::string > split (const std::string &str, char delimiter)
void clear (int limit)
Function Documentation
clear()
void clear (int limit)
Definition at line 125 of file toolkit.cpp.
{
    for (int i = 0; i < limit; i++)
    {
        std::cout << "\033[A\033[K";
        std::cout.flush();
        // sleep(1);
    }
}
Referenced by TicTacToe::computerTurn(), CodeGuesser::start(), and TicTacToe::startGame().
delay()
void delay (int milliseconds)
Definition at line 29 of file toolkit.cpp.
{
    auto start = std::chrono::high_resolution_clock::now();
    while (std::chrono::high_resolution_clock::now() - start < std::chrono::milliseconds(milliseconds))
    {
        // Busy-waiting loop to create a delay
    }
}
Referenced by typePrint().
disableInput()
void disableInput ()
Definition at line 39 of file toolkit.cpp.
{
#ifdef _WIN32
    HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE);
    SetConsoleMode(hStdin, 0);
#else
    struct termios t;
    tcgetattr(STDIN_FILENO, &t);
    t.c_lflag &= ~ICANON; // Disable canonical mode
    t.c_lflag &= ~ECHO;   // Disable echo
    tcsetattr(STDIN_FILENO, TCSANOW, &t);
#endif
}
Referenced by typePrint().
enableInput()
void enableInput ()
Definition at line 54 of file toolkit.cpp.
{
#ifdef _WIN32
    HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE);
    SetConsoleMode(hStdin, ENABLE_ECHO_INPUT | ENABLE_INSERT_MODE | ENABLE_LINE_INPUT | ENABLE_MOUSE_INPUT | ENABLE_PROCESSED_INPUT | ENABLE_QUICK_EDIT_MODE | ENABLE_WINDOW_INPUT | ENABLE_VIRTUAL_TERMINAL_INPUT);
#else
    struct termios t;
    tcgetattr(STDIN_FILENO, &t);
    t.c_lflag |= ICANON; // Enable canonical mode
    t.c_lflag |= ECHO;   // Enable echo
    tcsetattr(STDIN_FILENO, TCSANOW, &t);
    tcflush(STDIN_FILENO, TCIFLUSH);
#endif
}
Referenced by typePrint().
getFileContent()
std::string getFileContent (std::string fileName)
Definition at line 98 of file toolkit.cpp.
{
    std::ifstream file(fileName);
    std::string str;
    std::string file_contents;
    while (std::getline(file, str))
    {
        file_contents += str;
        file_contents.push_back('\n');
    }
    return file_contents;
}
SetTerminalSize()
void SetTerminalSize (int height, int width)
Definition at line 22 of file toolkit.cpp.
{
    std::cout << "\e[8;50;100t";
}
Referenced by main().
split()
std::vector< std::string > split (const std::string & str, char delimiter)
Definition at line 111 of file toolkit.cpp.
{
    std::vector<std::string> tokens;
    std::string token;
    std::istringstream tokenStream(str);
    while (std::getline(tokenStream, token, delimiter))
    {
        tokens.push_back(token);
    }
    return tokens;
}
typePrint()
void typePrint (std::string content)
Definition at line 70 of file toolkit.cpp.
{
    std::string token;
    std::stringstream ss(content);
    std::vector<std::string> tokens;
    while (getline(ss, token, '@'))
    {
        tokens.push_back(token);
    }
    disableInput();
    for (std::string &text : tokens)
    {
        for (char c : text)
        {
            std::cout << "\033[36m" << c << std::flush;
            delay(25);
        }
        enableInput();
        while (getchar() != '\n')
        {
        }
        disableInput();
    }
    enableInput();
}
References delay(), disableInput(), and enableInput().